@useCookieStore

### Register User
POST http://localhost:3009/api/v1/auth/register
Content-Type: application/json

{
  "email": "testuser12@example.com",
  "password": "Test@1234",
  "displayName": "Test User"
}

### Login User
POST http://localhost:3009/api/v1/auth/login
Content-Type: application/json

{
  "email": "testuser12@example.com",
  "password": "Test@1234"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}


### Refresh Access Token
POST http://localhost:3009/api/v1/auth/refresh
Content-Type: application/json

# ⛔️ DO NOT set Authorization header here
# ⛔️ The cookie will send refreshToken automatically

POST http://localhost:3009/api/v1/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTAzN2FkMzljOWFiYTRjMzQ4MTExNyIsImlhdCI6MTc0NTg5MzMwMSwiZXhwIjoxNzQ2NDk4MTAxfQ.fa7RximFohEnkIlYmpqTHC-BCGPSLT0J6PuN6m4Qdu0
Content-Type: application/json


### Logout
POST http://localhost:3009/api/v1/auth/logout
Content-Type: application/json
